### ISSUE TITLE
Interceptor has issues

### ISSUE THREAD

**Issue by beothorn** [beothorn/javaflame#75]
➜  javaflame git:(main) ✗ java "-javaagent:./javaAgent/build/libs/javaAgent.jar=intercept:com.github.beothorn.sorts.algorithms.InplaceQuickSort#findNextValueBiggerOrEqualThanPivotOnLeft>com.github.beothorn.tests.Interceptor#interceptMethod" -jar ./javaExampleApp/build/libs/javaExampleApp.jar
[JAVA_AGENT] INFO Agent loaded
[JAVA_AGENT] INFO Output at /tmp/javaflame4149505471066219912/1713392286660_snap
java.lang.IllegalStateException: Cannot map this reference for static method or constructor start: private static int com.github.beothorn.sorts.algorithms.InplaceQuickSort.findNextValueBiggerOrEqualThanPivotOnLeft(int,int,int[])
	at net.bytebuddy.asm.Advice$OffsetMapping$ForThisReference.resolve(Advice.java:2002)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$ForMethodExit.doApply(Advice.java:9873)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$ForMethodExit.apply(Advice.java:9831)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$AdviceMethodInliner.visitMethod(Advice.java:9237)
	at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1353)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:744)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:424)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$AdviceMethodInliner.apply(Advice.java:9230)
	at net.bytebuddy.asm.Advice$AdviceVisitor$WithExitAdvice.onUserEnd(Advice.java:11780)
	at net.bytebuddy.asm.Advice$AdviceVisitor.visitMaxs(Advice.java:11559)
	at net.bytebuddy.jar.asm.MethodVisitor.visitMaxs(MethodVisitor.java:786)
	at net.bytebuddy.jar.asm.MethodVisitor.visitMaxs(MethodVisitor.java:786)
	at net.bytebuddy.asm.Advice$AdviceVisitor.visitMaxs(Advice.java:11560)
	at net.bytebuddy.jar.asm.ClassReader.readCode(ClassReader.java:2666)
	at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1514)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:744)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:424)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:4014)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2224)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$UsingTypeWriter.make(DynamicType.java:4062)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:12458)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:12393)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1800(AgentBuilder.java:12102)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:12800)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:12740)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doPrivileged(AgentBuilder.java)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:12302)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.github.beothorn.App.main(App.java:29)

**Comment by beothorn** [comment]
Fixed
