### ISSUE TITLE
Fail on simple not operator

### ISSUE THREAD

**Issue by beothorn** [beothorn/javaflame#80]
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:560)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:572)
Caused by: java.lang.RuntimeException: com.github.beothorn.agent.parser.CompilationException: Invalid input: ! can appear only on start of string: "\[!]Test"
	at com.github.beothorn.agent.MethodInstrumentationAgent.lambda$maybeAddFilter$4(MethodInstrumentationAgent.java:180)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.github.beothorn.agent.MethodInstrumentationAgent.maybeAddFilter(MethodInstrumentationAgent.java:174)
	at com.github.beothorn.agent.MethodInstrumentationAgent.premain(MethodInstrumentationAgent.java:128)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 3 more
Caused by: com.github.beothorn.agent.parser.CompilationException: Invalid input: ! can appear only on start of string: "\[!]Test"
	at com.github.beothorn.agent.parser.Lexer.readNextToken(Lexer.java:101)
	at com.github.beothorn.agent.parser.Lexer.tokenize(Lexer.java:26)
	at com.github.beothorn.agent.parser.ElementMatcherFromExpression.forExpression(ElementMatcherFromExpression.java:19)
	at com.github.beothorn.agent.MethodInstrumentationAgent.lambda$maybeAddFilter$4(MethodInstrumentationAgent.java:177)

**Comment by beothorn** [comment]
java "-javaagent:./javaAgent/build/libs/javaAgent.jar=out:./outputs/notTest,filter:\!Test" -jar ./javaExampleApp/build/libs/javaExampleApp.jar

**Comment by beothorn** [comment]
Now it works?????
