### ISSUE TITLE
java 11/21 not working with java8  

### ISSUE THREAD

**Issue by maxandersen** [beothorn/javaflame#96]
should i not be able to run java 8 classes with java 11 or 21?

running a java 8 set of classes with java 11 and java 11 dependency give me this error:

```
jbang --java 11 --javaagent com.github.beothorn:javaFlame:25.0.0:java11 env@jbangdev
[JAVA_AGENT] INFO Agent v25.0.0 loaded
[JAVA_AGENT] INFO Output at /var/folders/rb/jl238yks5xg62d0brw32jbd40000gn/T/javaflame14323169489287895329/1728207395361_snap
Exception in thread "main" java.lang.ClassFormatError: Class file version does not support constant tag 15 in class file picocli/CommandLine
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1022)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
        at env.main(env.java:37)
[JAVA_AGENT] INFO Snapshot '/var/folders/rb/jl238yks5xg62d0brw32jbd40000gn/T/javaflame14323169489287895329/1728207395361_snap/data.js'
[JAVA_AGENT] INFO Graph at '/var/folders/rb/jl238yks5xg62d0brw32jbd40000gn/T/javaflame14323169489287895329/1728207395361_snap/index.html'
```

can only make it work if I use java8 dependency:

` jbang --java 21 --javaagent com.github.beothorn:javaFlame:25.0.0:java8 env@jbangdev`

which seems to be hard to require as lots of projects will include mix of used java versions for the byte code.

**Comment by beothorn** [comment]
I am still investigating, but what I can say so far is that:
- The class with the issue picocli/CommandLine.class, actually was compiled with java 5
```
public class picocli.CommandLine
  minor version: 0
  major version: 49
 ```
-  I created a jar with mixed classes versions, 8, 11 and 17 and it apparently works.

My current theory is that the code injected by the agent is not compatible with java 5.
I will fix this, but I also will add some tests to ensure it will still run, and some code that throw warnings when an unknown java version is detected on the transformed class.
I also want to introduce some facilities to look at the final bytecode after transformation.

The workaround for now would be to filter out picocli.

**Comment by kimihanif** [comment]
Getting the same error when running with java 21 jar

Caused by: java.lang.ClassFormatError: Class file version does not support constant tag 15 in class file com/fasterxml/jackson/annotation/JsonProperty$Access

**Comment by beothorn** [comment]
![image](https://github.com/user-attachments/assets/0d2d194b-9a1d-4bba-b75d-45895f08680f)

The incompatible code seems to be the a try catch Exception on the Advice that intercepts all calls.
This is happening only for code compiled for java 5 (as far as I tested)

Removing it works, but unfortunately without a filter there are too many function calls and I get an out of memory exception, and the dump is too big.

By adding a filter "picocli" I was able to get a readabe graph.
`jbang --javaagent ./javaAgent-java11.jar=filter:picocli env@jbangdev`

I think there will always be an expectation it works without any argument.
Since this is only true for small applications, probably I will make future versions do not run without a filter or try somehow to find a good default filter.

@kimihanif Would it be possible to check the version of the jackson-annotations that is present on your project? I would like to confirm this is the same case as the picocli issue or something else.

**Comment by beothorn** [comment]
Experimenting with this class:  
```java
public class Echo11 {
    public static void main(String[] args) {
    }
}
```
Compiling with a java 5 target:  
`javac -source 5 -target 5 Echo11.java` 

Simplifying javaflame with only the code that fails (found through trial and error) and using the byte buddy system property to dump the generated class files:  
`-Dnet.bytebuddy.dump=/tmp/bbout2`

We can get the generated classfiles. One of these instructions is not supported when the class header major version is 49.  

Original:  
```
Classfile /tmp/bbout2/Echo11-original.1728847420005.class
  Last modified 13/10/2024; size 257 bytes
  MD5 checksum c0fc53c0dddce497959ab7fb59c20f42
  Compiled from "Echo11.java"
public class Echo11
  minor version: 0
  major version: 49
  flags: ACC_PUBLIC, ACC_SUPER
Constant pool:
   #1 = Methodref          #3.#12         // java/lang/Object."<init>":()V
   #2 = Class              #13            // Echo11
   #3 = Class              #14            // java/lang/Object
   #4 = Utf8               <init>
   #5 = Utf8               ()V
   #6 = Utf8               Code
   #7 = Utf8               LineNumberTable
   #8 = Utf8               main
   #9 = Utf8               ([Ljava/lang/String;)V
  #10 = Utf8               SourceFile
  #11 = Utf8               Echo11.java
  #12 = NameAndType        #4:#5          // "<init>":()V
  #13 = Utf8               Echo11
  #14 = Utf8               java/lang/Object
{
  public Echo11();
    descriptor: ()V
    flags: ACC_PUBLIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #1                  // Method java/lang/Object."<init>":()V
         4: return
      LineNumberTable:
        line 1: 0

  public static void main(java.lang.String[]);
    descriptor: ([Ljava/lang/String;)V
    flags: ACC_PUBLIC, ACC_STATIC
    Code:
      stack=0, locals=1, args_size=1
         0: return
      LineNumberTable:
        line 3: 0
}
SourceFile: "Echo11.java"
```

Modified:  
```
Classfile /tmp/bbout2/Echo11.1728847420005.class
  Last modified 13/10/2024; size 881 bytes
  MD5 checksum 3f80ce19e81e58b18b212b1a1fe03894
  Compiled from "Echo11.java"
public class Echo11
  minor version: 0
  major version: 49
  flags: ACC_PUBLIC, ACC_SUPER
Constant pool:
   #1 = Methodref          #3.#12         // java/lang/Object."<init>":()V
   #2 = Class              #13            // Echo11
   #3 = Class              #14            // java/lang/Object
   #4 = Utf8               <init>
   #5 = Utf8               ()V
   #6 = Utf8               Code
   #7 = Utf8               LineNumberTable
   #8 = Utf8               main
   #9 = Utf8               ([Ljava/lang/String;)V
  #10 = Utf8               SourceFile
  #11 = Utf8               Echo11.java
  #12 = NameAndType        #4:#5          // "<init>":()V
  #13 = Utf8               Echo11
  #14 = Utf8               java/lang/Object
  #15 = Utf8               java/lang/Exception
  #16 = Class              #15            // java/lang/Exception
  #17 = Utf8               java/lang/System
  #18 = Class              #17            // java/lang/System
  #19 = Utf8               out
  #20 = Utf8               Ljava/io/PrintStream;
  #21 = NameAndType        #19:#20        // out:Ljava/io/PrintStream;
  #22 = Fieldref           #18.#21        // java/lang/System.out:Ljava/io/PrintStream;
  #23 = Utf8               getMessage
  #24 = Utf8               ()Ljava/lang/String;
  #25 = NameAndType        #23:#24        // getMessage:()Ljava/lang/String;
  #26 = Methodref          #16.#25        // java/lang/Exception.getMessage:()Ljava/lang/String;
  #27 = Utf8               w dw
  #28 = String             #27            // w dw
  #29 = Utf8               java/lang/invoke/StringConcatFactory
  #30 = Class              #29            // java/lang/invoke/StringConcatFactory
  #31 = Utf8               makeConcatWithConstants
  #32 = Utf8               (Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite;
  #33 = NameAndType        #31:#32        // makeConcatWithConstants:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite;
  #34 = Methodref          #30.#33        // java/lang/invoke/StringConcatFactory.makeConcatWithConstants:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite;
  #35 = MethodHandle       #6:#34         // invokestatic java/lang/invoke/StringConcatFactory.makeConcatWithConstants:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite;
  #36 = Utf8               (Ljava/lang/String;)Ljava/lang/String;
  #37 = NameAndType        #31:#36        // makeConcatWithConstants:(Ljava/lang/String;)Ljava/lang/String;
  #38 = InvokeDynamic      #0:#37         // #0:makeConcatWithConstants:(Ljava/lang/String;)Ljava/lang/String;
  #39 = Utf8               java/io/PrintStream
  #40 = Class              #39            // java/io/PrintStream
  #41 = Utf8               println
  #42 = Utf8               (Ljava/lang/String;)V
  #43 = NameAndType        #41:#42        // println:(Ljava/lang/String;)V
  #44 = Methodref          #40.#43        // java/io/PrintStream.println:(Ljava/lang/String;)V
  #45 = Utf8               java/lang/Throwable
  #46 = Class              #45            // java/lang/Throwable
  #47 = Utf8               BootstrapMethods
{
  public Echo11();
    descriptor: ()V
    flags: ACC_PUBLIC
    Code:
      stack=2, locals=2, args_size=1
         0: iconst_2
         1: istore_1
         2: goto          21
         5: astore_1
         6: getstatic     #22                 // Field java/lang/System.out:Ljava/io/PrintStream;
         9: aload_1
        10: invokevirtual #26                 // Method java/lang/Exception.getMessage:()Ljava/lang/String;
        13: invokedynamic #38,  0             // InvokeDynamic #0:makeConcatWithConstants:(Ljava/lang/String;)Ljava/lang/String;
        18: invokevirtual #44                 // Method java/io/PrintStream.println:(Ljava/lang/String;)V
        21: goto          24
        24: nop
        25: aload_0
        26: invokespecial #1                  // Method java/lang/Object."<init>":()V
        29: return
      Exception table:
         from    to  target type
             0     2     5   Class java/lang/Exception
      LineNumberTable:
        line 1: 0

  public static void main(java.lang.String[]);
    descriptor: ([Ljava/lang/String;)V
    flags: ACC_PUBLIC, ACC_STATIC
    Code:
      stack=1, locals=3, args_size=1
         0: goto          3
         3: aload_0
         4: astore_1
         5: nop
         6: goto          9
         9: aconst_null
        10: astore_1
        11: goto          15
        14: astore_1
        15: goto          18
        18: aload_1
        19: ifnull        24
        22: aload_1
        23: athrow
        24: return
      Exception table:
         from    to  target type
             6     9    14   Class java/lang/Throwable
      LineNumberTable:
        line 3: 0
}
SourceFile: "Echo11.java"
BootstrapMethods:
  0: #35 invokestatic java/lang/invoke/StringConcatFactory.makeConcatWithConstants:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite;
    Method arguments:
      #28 w dw
```

**Comment by beothorn** [comment]
Isolated error to a String concatenation:
```
package com.github.beothorn.agent.advice;

import net.bytebuddy.asm.Advice.*;

import java.lang.reflect.Constructor;
public class AdviceConstructorCallRecorderWithCapture {

    @OnMethodEnter
    public static void enter(
        @Origin Constructor<?> constructor,
        @AllArguments Object[] allArguments
    ) {
        String a = "ddd";
        String b = "ddda";
        System.out.println(a+b);
    }
}
```

This somehow relates to:
```
#35 = MethodHandle       #6:#34         // invokestatic java/lang/invoke/StringConcatFactory.makeConcatWithConstants:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite;
```
But, when writing a simple byte buddy agent that injects the exact same code, it generates bytecode without the MethodHandle.

```
Classfile /tmp/good2/Echo11.1728850731985.class
  Last modified 13/10/2024; size 1202 bytes
  MD5 checksum f3fa0e950db42ab8669e7c17951fd30a
  Compiled from "Echo11.java"
public class Echo11
  minor version: 0
  major version: 49
  flags: ACC_PUBLIC, ACC_SUPER
Constant pool:
   #1 = Methodref          #3.#12         // java/lang/Object."<init>":()V
   #2 = Class              #13            // Echo11
   #3 = Class              #14            // java/lang/Object
   #4 = Utf8               <init>
   #5 = Utf8               ()V
   #6 = Utf8               Code
   #7 = Utf8               LineNumberTable
   #8 = Utf8               main
   #9 = Utf8               ([Ljava/lang/String;)V
  #10 = Utf8               SourceFile
  #11 = Utf8               Echo11.java
  #12 = NameAndType        #4:#5          // "<init>":()V
  #13 = Utf8               Echo11
  #14 = Utf8               java/lang/Object
  #15 = Utf8               ddd
  #16 = String             #15            // ddd
  #17 = Utf8               ddda
  #18 = String             #17            // ddda
  #19 = Utf8               java/lang/System
  #20 = Class              #19            // java/lang/System
  #21 = Utf8               out
  #22 = Utf8               Ljava/io/PrintStream;
  #23 = NameAndType        #21:#22        // out:Ljava/io/PrintStream;
  #24 = Fieldref           #20.#23        // java/lang/System.out:Ljava/io/PrintStream;
  #25 = Utf8               java/lang/StringBuilder
  #26 = Class              #25            // java/lang/StringBuilder
  #27 = Methodref          #26.#12        // java/lang/StringBuilder."<init>":()V
  #28 = Utf8               append
  #29 = Utf8               (Ljava/lang/String;)Ljava/lang/StringBuilder;
  #30 = NameAndType        #28:#29        // append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
  #31 = Methodref          #26.#30        // java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
  #32 = Utf8               toString
  #33 = Utf8               ()Ljava/lang/String;
  #34 = NameAndType        #32:#33        // toString:()Ljava/lang/String;
  #35 = Methodref          #26.#34        // java/lang/StringBuilder.toString:()Ljava/lang/String;
  #36 = Utf8               java/io/PrintStream
  #37 = Class              #36            // java/io/PrintStream
  #38 = Utf8               println
  #39 = Utf8               (Ljava/lang/String;)V
  #40 = NameAndType        #38:#39        // println:(Ljava/lang/String;)V
  #41 = Methodref          #37.#40        // java/io/PrintStream.println:(Ljava/lang/String;)V
  #42 = Utf8               <clinit>
  #43 = Utf8               java/lang/ClassLoader
  #44 = Class              #43            // java/lang/ClassLoader
  #45 = Utf8               getSystemClassLoader
  #46 = Utf8               ()Ljava/lang/ClassLoader;
  #47 = NameAndType        #45:#46        // getSystemClassLoader:()Ljava/lang/ClassLoader;
  #48 = Methodref          #44.#47        // java/lang/ClassLoader.getSystemClassLoader:()Ljava/lang/ClassLoader;
  #49 = Utf8               net.bytebuddy.dynamic.Nexus
  #50 = String             #49            // net.bytebuddy.dynamic.Nexus
  #51 = Utf8               loadClass
  #52 = Utf8               (Ljava/lang/String;)Ljava/lang/Class;
  #53 = NameAndType        #51:#52        // loadClass:(Ljava/lang/String;)Ljava/lang/Class;
  #54 = Methodref          #44.#53        // java/lang/ClassLoader.loadClass:(Ljava/lang/String;)Ljava/lang/Class;
  #55 = Utf8               initialize
  #56 = String             #55            // initialize
  #57 = Utf8               java/lang/Class
  #58 = Class              #57            // java/lang/Class
  #59 = Utf8               java/lang/Integer
  #60 = Class              #59            // java/lang/Integer
  #61 = Utf8               TYPE
  #62 = Utf8               Ljava/lang/Class;
  #63 = NameAndType        #61:#62        // TYPE:Ljava/lang/Class;
  #64 = Fieldref           #60.#63        // java/lang/Integer.TYPE:Ljava/lang/Class;
  #65 = Utf8               getMethod
  #66 = Utf8               (Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;
  #67 = NameAndType        #65:#66        // getMethod:(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;
  #68 = Methodref          #58.#67        // java/lang/Class.getMethod:(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;
  #69 = Integer            -1502853322
  #70 = Utf8               valueOf
  #71 = Utf8               (I)Ljava/lang/Integer;
  #72 = NameAndType        #70:#71        // valueOf:(I)Ljava/lang/Integer;
  #73 = Methodref          #60.#72        // java/lang/Integer.valueOf:(I)Ljava/lang/Integer;
  #74 = Utf8               java/lang/reflect/Method
  #75 = Class              #74            // java/lang/reflect/Method
  #76 = Utf8               invoke
  #77 = Utf8               (Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
  #78 = NameAndType        #76:#77        // invoke:(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
  #79 = Methodref          #75.#78        // java/lang/reflect/Method.invoke:(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
{
  public Echo11();
    descriptor: ()V
    flags: ACC_PUBLIC
    Code:
      stack=3, locals=3, args_size=1
         0: ldc           #16                 // String ddd
         2: astore_1
         3: ldc           #18                 // String ddda
         5: astore_2
         6: getstatic     #24                 // Field java/lang/System.out:Ljava/io/PrintStream;
         9: new           #26                 // class java/lang/StringBuilder
        12: dup
        13: invokespecial #27                 // Method java/lang/StringBuilder."<init>":()V
        16: aload_1
        17: invokevirtual #31                 // Method java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
        20: aload_2
        21: invokevirtual #31                 // Method java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
        24: invokevirtual #35                 // Method java/lang/StringBuilder.toString:()Ljava/lang/String;
        27: invokevirtual #41                 // Method java/io/PrintStream.println:(Ljava/lang/String;)V
        30: goto          33
        33: nop
        34: aload_0
        35: invokespecial #1                  // Method java/lang/Object."<init>":()V
        38: return
      LineNumberTable:
        line 1: 0

  public static void main(java.lang.String[]);
    descriptor: ([Ljava/lang/String;)V
    flags: ACC_PUBLIC, ACC_STATIC
    Code:
      stack=0, locals=1, args_size=1
         0: return
      LineNumberTable:
        line 3: 0

  static {};
    descriptor: ()V
    flags: ACC_STATIC
    Code:
      stack=6, locals=0, args_size=0
         0: invokestatic  #48                 // Method java/lang/ClassLoader.getSystemClassLoader:()Ljava/lang/ClassLoader;
         3: ldc           #50                 // String net.bytebuddy.dynamic.Nexus
         5: invokevirtual #54                 // Method java/lang/ClassLoader.loadClass:(Ljava/lang/String;)Ljava/lang/Class;
         8: ldc           #56                 // String initialize
        10: iconst_2
        11: anewarray     #58                 // class java/lang/Class
        14: dup
        15: iconst_0
        16: ldc           #58                 // class java/lang/Class
        18: aastore
        19: dup
        20: iconst_1
        21: getstatic     #64                 // Field java/lang/Integer.TYPE:Ljava/lang/Class;
        24: aastore
        25: invokevirtual #68                 // Method java/lang/Class.getMethod:(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;
        28: aconst_null
        29: iconst_2
        30: anewarray     #3                  // class java/lang/Object
        33: dup
        34: iconst_0
        35: ldc           #2                  // class Echo11
        37: aastore
        38: dup
        39: iconst_1
        40: ldc           #69                 // int -1502853322
        42: invokestatic  #73                 // Method java/lang/Integer.valueOf:(I)Ljava/lang/Integer;
        45: aastore
        46: invokevirtual #79                 // Method java/lang/reflect/Method.invoke:(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
        49: pop
        50: return
}
SourceFile: "Echo11.java"
```

**Comment by beothorn** [comment]
The error was hidden by this line of code:  
`AgentBuilder agentBuilder = new AgentBuilder.Default(new ByteBuddy().with(TypeValidation.DISABLED));`  
The type validation was disabled because dependencies compiled with scala can use Java reserved words llike default, and this was failing when instrumenting these scala classes.  

When this is removed another exception is thrown.  
```java
java.lang.IllegalStateException: Cannot write invoke dynamic instruction for class file version Java 5 (49)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ValidatingClassVisitor$Constraint$ForClassFileVersion.assertInvokeDynamic(TypeWriter.java:3532)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ValidatingClassVisitor$Constraint$Compound.assertInvokeDynamic(TypeWriter.java:3720)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ValidatingClassVisitor$ValidatingMethodVisitor.visitInvokeDynamicInsn(TypeWriter.java:3859)
	at net.bytebuddy.jar.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:474)
	at net.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.onVisitInvokeDynamicInsn(ExceptionTableSensitiveMethodVisitor.java:217)
	at net.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.visitInvokeDynamicInsn(ExceptionTableSensitiveMethodVisitor.java:205)
	at net.bytebuddy.jar.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:474)
	at net.bytebuddy.utility.visitor.StackAwareMethodVisitor.visitInvokeDynamicInsn(StackAwareMethodVisitor.java:378)
	at net.bytebuddy.jar.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:474)
	at net.bytebuddy.utility.visitor.StackAwareMethodVisitor.visitInvokeDynamicInsn(StackAwareMethodVisitor.java:378)
	at net.bytebuddy.jar.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:474)
	at net.bytebuddy.jar.asm.MethodVisitor.visitInvokeDynamicInsn(MethodVisitor.java:474)
	at net.bytebuddy.jar.asm.ClassReader.readCode(ClassReader.java:2475)
	at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1514)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:744)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:424)
	at net.bytebuddy.asm.Advice$Dispatcher$Inlining$Resolved$AdviceMethodInliner.apply(Advice.java:9230)
	at net.bytebuddy.asm.Advice$AdviceVisitor.onAfterExceptionTable(Advice.java:11524)
	at net.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.considerEndOfExceptionTable(ExceptionTableSensitiveMethodVisitor.java:49)
	at net.bytebuddy.utility.visitor.ExceptionTableSensitiveMethodVisitor.visitLabel(ExceptionTableSensitiveMethodVisitor.java:81)
	at net.bytebuddy.jar.asm.Label.accept(Label.java:362)
	at net.bytebuddy.jar.asm.ClassReader.readCode(ClassReader.java:2058)
	at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1514)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:744)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:424)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:4014)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2224)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$UsingTypeWriter.make(DynamicType.java:4062)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:12458)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:12393)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1800(AgentBuilder.java:12102)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:12880)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:12812)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doPrivileged(AgentBuilder.java)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:12336)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:610)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:803)
	at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:698) 
```

Without the string concatenation this particular issue is fixed (but there are other issues with picocli)  
https://github.com/beothorn/javaflame/commit/ba2a2dde66017cf554d255e6f1bb8b15d28243f9  
This issue will be closed on release 26

**Comment by beothorn** [comment]
`jbang --java 21 --javaagent com.github.beothorn:javaFlame:26.0.0:java8 env@jbangdev` runs fine now
